-- ============================================================
-- H2 TEST SCHEMA
-- ============================================================

-- ============================================================
-- DROP TABLES
-- ============================================================

DROP TABLE IF EXISTS videogames_platforms;
DROP TABLE IF EXISTS videogame_game_genre;
DROP TABLE IF EXISTS tv_genre;
DROP TABLE IF EXISTS movie_genre;
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS refresh_token;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS profiles;
DROP TABLE IF EXISTS videogames;
DROP TABLE IF EXISTS platforms;
DROP TABLE IF EXISTS game_genre;
DROP TABLE IF EXISTS tv_shows;
DROP TABLE IF EXISTS movies;
DROP TABLE IF EXISTS showcases;
DROP TABLE IF EXISTS genres;
DROP TABLE IF EXISTS games;


-- ============================================================
-- BASE TABLES
-- ============================================================

CREATE TABLE game_genre (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_rawg INT,
    name VARCHAR(255),
    game_count INT,
    CONSTRAINT id_genre_UNIQUE UNIQUE (id_rawg)
);


CREATE TABLE games (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(100),
    name VARCHAR(20)
);


CREATE TABLE genres (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tmdb_id INT,
    name CLOB,
    CONSTRAINT id_UNIQUE UNIQUE (tmdb_id)
);


CREATE TABLE movies (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tmdb_id INT,
    title VARCHAR(255),
    resume CLOB,
    release_date DATE,
    language VARCHAR(255),
    poster_path VARCHAR(255),
    backdrop_path VARCHAR(255),
    popularity REAL,
    vote_average REAL,
    vote_count INT,
    CONSTRAINT movies_id_UNIQUE UNIQUE (id),
    CONSTRAINT movies_tmdb_id_UNIQUE UNIQUE (tmdb_id)
);


CREATE TABLE platforms (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_rawg INT,
    name VARCHAR(255),
    game_count INT,
    CONSTRAINT id_RAWG_UNIQUE UNIQUE (id_rawg)
);


CREATE TABLE profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    icon_id INT
);


CREATE TABLE roles (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(20),
    CONSTRAINT roles_name_check
        CHECK (name IN ('ROLE_USER', 'ROLE_MODERATOR', 'ROLE_ADMIN'))
);


CREATE TABLE showcases (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(100),
    name VARCHAR(20)
);


CREATE TABLE tv_shows (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tmdb_id INT,
    title VARCHAR(255),
    resume CLOB,
    first_air_date DATE,
    original_language VARCHAR(255),
    poster_path VARCHAR(255),
    backdrop_path VARCHAR(255),
    popularity REAL,
    vote_average REAL,
    vote_count INT,
    CONSTRAINT tv_shows_id_UNIQUE UNIQUE (id),
    CONSTRAINT tv_shows_tmdb_id_UNIQUE UNIQUE (tmdb_id)
);


CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(50),
    password VARCHAR(120),
    username VARCHAR(20),
    profile_id BIGINT,
    CONSTRAINT users_username_UNIQUE UNIQUE (username),
    CONSTRAINT users_email_UNIQUE UNIQUE (email)
);


CREATE TABLE videogames (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rawg_id INT,
    name VARCHAR(255),
    released DATE,
    rating REAL,
    rating_count INT,
    metacritics INT,
    image_url VARCHAR(255),
    CONSTRAINT rawg_id_UNIQUE UNIQUE (rawg_id)
);


-- ============================================================
-- RELATION TABLES
-- ============================================================

CREATE TABLE movie_genre (
    movie_id INT NOT NULL,
    genre_id INT NOT NULL,
    PRIMARY KEY (movie_id, genre_id),

    CONSTRAINT movie_genre_movie_fk
        FOREIGN KEY (movie_id)
        REFERENCES movies (tmdb_id)
        ON DELETE CASCADE,

    CONSTRAINT movie_genre_genre_fk
        FOREIGN KEY (genre_id)
        REFERENCES genres (tmdb_id)
        ON DELETE CASCADE
);


CREATE TABLE tv_genre (
    tv_id INT NOT NULL,
    genre_id INT NOT NULL,
    PRIMARY KEY (tv_id, genre_id),

    CONSTRAINT tv_genre_tv_fk
        FOREIGN KEY (tv_id)
        REFERENCES tv_shows (tmdb_id)
        ON DELETE CASCADE,

    CONSTRAINT tv_genre_genre_fk
        FOREIGN KEY (genre_id)
        REFERENCES genres (tmdb_id)
        ON DELETE CASCADE
);


CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    role_id INT NOT NULL,
    PRIMARY KEY (user_id, role_id),

    CONSTRAINT user_roles_role_fk
        FOREIGN KEY (role_id)
        REFERENCES roles (id),

    CONSTRAINT user_roles_user_fk
        FOREIGN KEY (user_id)
        REFERENCES users (id)
);


CREATE TABLE refresh_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token VARCHAR(255) NOT NULL,
    revoked BOOLEAN NOT NULL,
    expiring TIMESTAMP NOT NULL,

    CONSTRAINT refresh_token_id_UNIQUE UNIQUE (id),

    CONSTRAINT refresh_token_user_fk
        FOREIGN KEY (user_id)
        REFERENCES users (id)
);


CREATE TABLE videogame_game_genre (
    id_video_game INT NOT NULL,
    id_game_genre INT NOT NULL,
    PRIMARY KEY (id_video_game, id_game_genre),

    CONSTRAINT videogame_game_genre_game_fk
        FOREIGN KEY (id_video_game)
        REFERENCES videogames (rawg_id)
        ON DELETE CASCADE,

    CONSTRAINT videogame_game_genre_genre_fk
        FOREIGN KEY (id_game_genre)
        REFERENCES game_genre (id_rawg)
        ON DELETE CASCADE
);


CREATE TABLE videogames_platforms (
    id_videogame INT NOT NULL,
    id_platforms INT NOT NULL,
    PRIMARY KEY (id_videogame, id_platforms),

    CONSTRAINT videogames_platforms_videogame_fk
        FOREIGN KEY (id_videogame)
        REFERENCES videogames (rawg_id)
        ON DELETE CASCADE,

    CONSTRAINT videogames_platforms_platform_fk
        FOREIGN KEY (id_platforms)
        REFERENCES platforms (id_rawg)
        ON DELETE CASCADE
);


-- ============================================================
-- INDEXES
-- ============================================================

CREATE INDEX refresh_token_user_idx
    ON refresh_token (user_id);

CREATE INDEX user_roles_role_idx
    ON user_roles (role_id);

CREATE INDEX movie_genre_genre_idx
    ON movie_genre (genre_id);

CREATE INDEX tv_genre_genre_idx
    ON tv_genre (genre_id);

CREATE INDEX videogame_game_genre_genre_idx
    ON videogame_game_genre (id_game_genre);

CREATE INDEX videogames_platforms_platform_idx
    ON videogames_platforms (id_platforms);


-- ============================================================
-- END
-- ============================================================